global:
  scrape_interval: 15s  # Tiempo entre cada recolección de métricas

scrape_configs:
  - job_name: 'dotnet_metrics'
    metrics_path: '/metrics'
    scheme: 'https'
    tls_config:
      insecure_skip_verify: true  # Para desarrollo, omitir verificación del certificado
    static_configs:
      - targets: ['192.168.18.78:44303']
